project_id = "gvqvrmkizemwsasmupmo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[functions.auth-login]
verify_jwt = false

[functions.update-password]
verify_jwt = true

[functions.enamed-proxy]
verify_jwt = false

[functions.study-guide-proxy]
verify_jwt = false

[functions.cronograma-enamed-proxy]
verify_jwt = false

[functions.session-security]
verify_jwt = true

[functions.b2c-signup]
verify_jwt = false

[functions.b2b-create-user]
verify_jwt = false

[functions.custom-email-templates]
verify_jwt = false

[functions.get-study-contents]
verify_jwt = true

[functions.save-calendar-arrangement]
verify_jwt = true

[functions.send-study-reminder]
verify_jwt = false

[functions.check-and-send-reminders]
verify_jwt = false

[functions.sync-user-auth]
verify_jwt = false