-- ============================================================================
-- ORDEM DE APLICACAO -- 3 PASSOS, NESSA ORDEM (07/08/2026)
--
-- Esta migration e SO o passo 3. As duas migrations deste PR NAO sao um bloco
-- so -- aplicar fora de ordem quebra o portal para TODO gestor, nao so para
-- quem hoje tem a feature desligada:
--   1) aplicar 20260807030000 -- as 11 RPCs get_gestor_* param de exigir
--      gestao.enabled; o front (useAccessRules.ts:35 na main de hoje) ainda
--      exige a chave, nada muda para o usuario (quem tinha a feature ligada
--      continua vendo o portal; quem nao tinha continua sem ver);
--   2) subir o front -- a mudanca de pr1/front (Task 1 do plano):
--      useAccessRules.ts para de ler hasFeature('gestao.enabled') e passa a
--      usar hasExperience(access, 'gestao');
--   3) SO ENTAO aplicar esta migration (20260807031000).
--
-- POR QUE A ORDEM IMPORTA AQUI -- QUEDA TOTAL, NAO JANELA INVISIVEL: apagar a
-- linha de gestao.enabled faz hasFeature('gestao.enabled') devolver false
-- para QUALQUER IES (mesmo coalesce(bool_or(enabled), false) sobre zero
-- linhas que a RPC user_has_feature faz -- ver o bloco mais abaixo, sobre as
-- 19 RPCs legadas). Enquanto o front ainda ler essa chave (passo 2 nao
-- feito), TODO gestor perde o portal -- nao so as IES que hoje tem a feature
-- desligada. E diferente do risco da 20260807030000 isolada: aquela e uma
-- janela SEM efeito perceptivel (o front continua bloqueando quem ja estava
-- bloqueado; nada piora). Esta aqui e queda visivel, imediata, para 100% dos
-- gestores, se aplicada antes do passo 2.
--
-- Este pre-requisito (passo 2) SOMA-SE ao pre-requisito de
-- GestorLayout.tsx/botoes Exportar+IA descrito no bloco abaixo -- os dois tem
-- de estar satisfeitos antes de aplicar; nenhum substitui o outro. Ver a
-- secao "Ordem de implantacao" em
-- docs/superpowers/plans/2026-08-07-simplificacao-acesso-gestor-pr1.md.
-- ============================================================================
--
-- PRE-REQUISITO ADICIONAL DE FRONT -- GestorLayout.tsx (exportar/ia)
--
-- Este DELETE tem uma dependencia no front que o spec original nao previa. A
-- premissa "gestao.exportar e gestao.ia sao dado morto, zero consumidores"
-- estava ERRADA para a main de hoje: src/experiences/gestor/GestorLayout.tsx
-- lia as duas chaves via useEffectiveFeatures/get_effective_features e com
-- elas renderizava os botoes "Exportar" e "IA" do header do /gestor e os
-- drawers correspondentes. hasFeature devolve false para chave inexistente,
-- entao apagar as linhas faz os dois botoes sumirem em silencio para TODO
-- gestor. A varredura original nao viu porque rodou na branch do PR #17, onde
-- o arquivo ja nao existe.
--
-- SO APLIQUE se ao menos uma destas for verdade:
--   (a) o commit "fix(gestor): Exportar e IA deixam de depender de
--       ies_features" ja esta na main E deployado (removeu o gate e travou o
--       comportamento em src/test/unit/gestorExportarIaSemFeature.test.tsx); ou
--   (b) o PR #17 (feat/portal-gestor-v2) ja esta mergeado E deployado -- ele
--       apaga src/experiences/gestor/ inteiro e o portal novo
--       (src/features/gestor/) nao referencia nenhuma das duas chaves.
--
-- Conferir na main, antes de aplicar. Este comando lista quem AINDA consome
-- qualquer chave 'gestao.*' -- e as 3 chaves apagadas aqui nao podem aparecer:
--   git grep -nE "hasFeature\(\s*['\"]gestao\." -- src/
--
-- Grepar so por "gestao.exportar" da falso positivo (pega comentario e o
-- proprio teste de regressao); e o hasFeature( que denuncia consumo real.
--
-- Resultado esperado: nenhuma linha com gestao.enabled, gestao.exportar ou
-- gestao.ia. Sobra so o teste de useAccessRules citando gestao.visao_institucional,
-- que nao e apagada aqui. Atencao: pr1/front conserta o consumidor de
-- gestao.enabled (useAccessRules.ts passa a usar hasExperience), mas NAO toca
-- GestorLayout.tsx -- os dois consumidores de exportar/ia sobrevivem a pr1/front.
--
-- Efeito colateral do fix (a), a conferir em producao (projeto gvqv, NAO lljn):
-- IES que hoje tenham gestao.exportar/gestao.ia = false, ou nenhuma linha,
-- passam a ver os dois botoes. Pelo seed de 09/07 todas as IES com gestor
-- ativo receberam as duas chaves = true, entao o esperado e zero afetadas:
--   SELECT feature_key, enabled, count(*)
--     FROM public.ies_features
--    WHERE feature_key IN ('gestao.exportar','gestao.ia')
--    GROUP BY 1,2 ORDER BY 1,2;
-- ============================================================================

-- Apaga as 3 chaves de gestao e a helper que ficou orfa.
-- Depende da migration anterior (20260807030000), que tirou o guard das 11
-- RPCs get_gestor_*. Dropar user_has_feature_for_ies com as 11 ainda
-- chamando-a quebraria todas -- por isso a ordem entre as duas migrations
-- importa.
-- NAO FOI APLICADA em producao (07/08/2026).
--
-- user_has_feature(text) NAO e tocada: 19 RPCs institucionais legadas ainda a
-- usam para chaves aluno.% e gestao.%. Para gestao.%, o efeito NAO e ficar
-- inerte -- e fail-closed. Em
-- 20260709171344_44671730-cd9c-4e8a-b003-49034839440e.sql:26-30, para toda
-- chave gestao.% DIFERENTE de gestao.enabled a funcao exige o master
-- (bool_or(enabled) sobre ies_features filtrado por feature_key =
-- 'gestao.enabled'; coalesce(..., false) se nao achar linha); e para a
-- propria chave gestao.enabled (:31-32), o mesmo coalesce(bool_or(enabled),
-- false) roda sobre ZERO linhas depois deste DELETE, o que da false. Ou seja:
-- depois desta migration, user_has_feature('gestao.*') passa a ser FALSE para
-- todo mundo que nao seja admin/atendimento (bypass de papel, linha 16 do
-- mesmo arquivo), e as RPCs legadas guardadas por ela levantam
-- 'feature_not_enabled'.
--
-- QUAIS: a lista completa esta no bloco DO daquele mesmo arquivo
-- (:113-166, mapping de :119-139) -- get_institutional_simulados,
-- get_institutional_performance, get_institutional_student_scores,
-- get_institutional_evolution, get_institutional_tri,
-- get_institutional_evolution_tri, get_ies_student_count (todas com guard
-- 'gestao.enabled') -- mais get_simulado_tem_tri (:49, guard hardcoded no
-- corpo da funcao, fora do bloco DO).
--
-- ALCANCE -- O QUE SE SABE E O QUE NAO SE SABE:
--   - em feat/portal-gestor-v2 (estado-alvo, PR #17) nao sobrou chamador vivo
--     dessas RPCs no front -- so um comentario em
--     src/components/admin/ies/IesFeaturesBoard.tsx:66, sem chamada real;
--   - na main de hoje elas estao vivas: src/pages/DesempenhoInstitucionalV2.tsx:71
--     e src/experiences/gestor/GestorFiltersProvider.tsx:59 as consomem, os
--     dois via useInstitutionalPerformanceData(filters);
--   - NAO DA PARA FECHAR O ALCANCE SO PELO REPOSITORIO: os guards destas 19
--     RPCs foram injetados em runtime por aquele bloco DO
--     (20260709171344...sql:113-166), reescrevendo pg_get_functiondef de cada
--     uma via EXECUTE -- o corpo real, ja com o guard aplicado, NAO ESTA em
--     nenhum .sql deste repo, so em producao. Uma varredura textual no
--     repositorio nao encontra (nem prova a ausencia de) outros chamadores
--     alem dos listados aqui.

DELETE FROM public.ies_features
 WHERE feature_key IN ('gestao.enabled', 'gestao.exportar', 'gestao.ia');

DELETE FROM public.feature_catalog
 WHERE key IN ('gestao.enabled', 'gestao.exportar', 'gestao.ia');

DROP FUNCTION IF EXISTS public.user_has_feature_for_ies(text, uuid);